# coco class selector
class : ['0']

# filter: coco class selection src and dst folders
src_label: '..\\..\\data\\coco2014\\labels\\train2014'
src_image: '..\\..\\data\\coco2014\\train2014'
dst_label: 'D:\data\coco2014_filtered\labels'
dst_image: 'D:\data\coco2014_filtered\images'

# train : valid : test
ratio: [0.7, 0.15 ,0.15]

# split dir with yolov5 format
split_yolov5: 'D:\data\coco2014_filtered\yolov5'
split_label: 'D:\data\train-camera-train\labels'
split_image: 'D:\data\train-camera-train\images'

# concat labels
slabel_dir: 'D:\data\head+body\coco\labels'
dlabel_dir: 'D:\data\head+body\coco\new'

# match
match_image_dir: 'D:\data\coco2014_filtered\images'
match_label_dir: 'D:\data\coco2014_filtered\labels'

# rename
rename_dir: 'D:\data\train-camera\helmet\images'